# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/JavaVulnerableLab-circle
    
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
    
      - checkout
      
      - run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - run: sudo su -c 'echo "deb http://deb.debian.org/debian jessie-backports main" >> /etc/apt/sources.list'
      - run: sudo rm -rf /var/lib/apt/lists/*
      - run: sudo apt-get update
      - run: sudo apt install -t jessie-backports  openjdk-8-jre-headless ca-certificates-java
      - run: sudo apt-get install python-setuptools
      - run: 
          command: |
            sudo git clone https://github.com/pyenv/pyenv.git /root/.pyenv
      - run: 
          command: | 
            echo 'export PATH="/root/.pyenv/bin:$PATH"' >> ~/.bashrc
            echo 'eval "$(pyenv init -)"' >> ~/.bashrc
            echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc          
      - run: bash <(curl -s -s https://scripts.scantist.com/ci-circle.sh)
